#!/usr/bin/env python3
"""
alert.py — Send error/status alerts via Resend email API.

Usage:
  python tools/alert.py "Subject line" "Body message"
  python tools/alert.py --dry-run "Subject line" "Body message"

Reads RESEND_API_KEY from .env. Sends to aiden@mindsparkstack.com.
Also logs all alerts to docs/ERROR_LOG.md.
Zero external dependencies — uses only Python standard library.
"""

import json
import os
import sys
from datetime import datetime
from urllib.request import Request, urlopen
from urllib.error import URLError, HTTPError

RESEND_API_URL = "https://api.resend.com/emails"
FROM_EMAIL = "MindSparkAI Alerts <onboarding@resend.dev>"
TO_EMAIL = os.getenv("ALERT_EMAIL", "")

# ---------------------------------------------------------------------------
# .env loader
# ---------------------------------------------------------------------------

def load_env(env_path):
    env = {}
    if not os.path.isfile(env_path):
        return env
    with open(env_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, value = line.split("=", 1)
            env[key.strip()] = value.strip().strip("'\"")
    return env

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

def log_to_error_log(subject, body, project_root):
    log_path = os.path.join(project_root, "docs", "ERROR_LOG.md")
    os.makedirs(os.path.dirname(log_path), exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    entry = f"\n## [{timestamp}] {subject}\n{body}\n"
    if os.path.isfile(log_path):
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(entry)
    else:
        with open(log_path, "w", encoding="utf-8") as f:
            f.write("# Error Log\n\nAutomatically generated by tools/alert.py.\n")
            f.write(entry)
    print(f"[LOG] Alert logged to docs/ERROR_LOG.md")

# ---------------------------------------------------------------------------
# Send email via Resend
# ---------------------------------------------------------------------------

def send_alert(api_key, subject, body, dry_run=False):
    if dry_run:
        print(f"[DRY-RUN] Would send alert email:")
        print(f"  From: {FROM_EMAIL}")
        print(f"  To: {TO_EMAIL}")
        print(f"  Subject: {subject}")
        print(f"  Body: {body[:200]}...")
        return True

    payload = json.dumps({
        "from": FROM_EMAIL,
        "to": [TO_EMAIL],
        "subject": f"[MindSparkAI Alert] {subject}",
        "text": body,
    }).encode("utf-8")

    req = Request(RESEND_API_URL, data=payload, method="POST")
    req.add_header("Authorization", f"Bearer {api_key}")
    req.add_header("Content-Type", "application/json")

    for attempt in range(3):
        try:
            with urlopen(req, timeout=15) as resp:
                result = json.loads(resp.read().decode("utf-8"))
                print(f"[OK] Alert email sent (id: {result.get('id', 'unknown')})")
                return True
        except HTTPError as e:
            print(f"[WARN] Attempt {attempt+1}/3 failed: HTTP {e.code} — {e.read().decode()}")
        except URLError as e:
            print(f"[WARN] Attempt {attempt+1}/3 failed: {e.reason}")

    print("[ERROR] All 3 attempts to send alert email failed.")
    return False

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    env = load_env(os.path.join(project_root, ".env"))

    api_key = env.get("RESEND_API_KEY")
    if not api_key:
        print("[ERROR] Missing RESEND_API_KEY in .env")
        sys.exit(1)

    # Set TO_EMAIL from .env
    global TO_EMAIL
    TO_EMAIL = env.get("ALERT_EMAIL", TO_EMAIL)
    if not TO_EMAIL:
        print("[ERROR] Missing ALERT_EMAIL in .env")
        sys.exit(1)

    args = sys.argv[1:]
    dry_run = False
    if "--dry-run" in args:
        dry_run = True
        args.remove("--dry-run")

    if len(args) < 2:
        print("Usage: python tools/alert.py [--dry-run] \"Subject\" \"Body\"")
        sys.exit(1)

    subject = args[0]
    body = args[1]

    log_to_error_log(subject, body, project_root)
    success = send_alert(api_key, subject, body, dry_run)
    sys.exit(0 if success else 1)

if __name__ == "__main__":
    main()
